# Das ist ein TOML-Dokument.
title = "TOML Beispiel"

[person]
name = "Tom Preston-Werner"
geburtstag = 1979-05-27T07:32:00-08:00

[datenbank]
adresse = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
verbindungen_max = 5000
# booleans
aktiviert = true

[servers]

  # Einruecken (sowohl Tabs als auch Leerzeichen) ist erlaubt, aber nicht erforderlich
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Zeilenumbrueche sind in Arrays moeglich
hosts = [
  "alpha",
  "omega"
]
